pipeline {
    agent any

    environment {
        // Add Terraform tool to PATH
        PATH = "${PATH}:${getTerraformPath()}"
        
        // Dynamic AMI name
        AMI_ID = "stack-ami-${BUILD_NUMBER}"
        VERSION = "1.0.${BUILD_NUMBER}"
    }

    stages {

        stage('Initial Stage') {
            steps {
                echo "Starting pipeline automatically..."
            }
        }

        stage('Packer AMI Build') {
            steps {
                slackSend(color: '#FFFF00', 
                    message: "STARTING PACKER IMAGE BUILD: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})"
                )

                sh '''
                    cd images

                    # Update AMI name
                    sed -i "s/ami-stack-[0-9]*/${AMI_ID}/" image.pkr.hcl

                    # Enable packer logging
                    export PACKER_LOG=1
                    export PACKER_LOG_PATH=$WORKSPACE/packer.log

                    # Call packer
                    packer build -force image.pkr.hcl
                '''
            }
        }

        stage('Terraform init') {
            steps {
                slackSend(color: '#FFFF00',
                    message: "STARTING TERRAFORM DEPLOYMENT: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})"
                )

                sh '''
                    cd instances
                    terraform init -upgrade
                '''
            }
        }

        stage('Terraform Plan') {
            steps {
                sh '''
                    cd instances
                    terraform plan -out=tfplan -input=false
                '''
            }
        }

        stage('Build Instance and Vulnerability Scan') {
            steps {
                slackSend(color: '#FFFF00',
                    message: "STARTING INFRASTRUCTURE BUILD AND VULNERABILITY SCAN: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})"
                )

                sh '''
                    cd instances
                    terraform apply -auto-approve
                '''
            }
        }

        stage('Build Vulnerability Report') {
            steps {
                sh '''
                    cd instances
                    aws inspector start-assessment-run \
                        --assessment-run-name Hardeningrun_'${VERSION}' \
                        --assessment-template-arn "arn:aws:inspector:us-east-1:336528460023:target/0-icADPfPR/template/0-vfjqO1E7" \
                        --region us-east-1
                '''

                slackSend(color: '#FFFF00',
                    message: "ENDING DEPLOYMENT: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})"
                )
            }
        }
    }
}

def getTerraformPath() {
    // Terraform installation configured under Jenkins Global Tool Configuration
    return tool(name: 'terraform-14', type: 'terraform')
}
